version: '3.8'
services:
  pokedex-nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./app/BACKEND:/app
      - /app/node_modules

    #command: sh -c "npm install && nodemon index.js"

  # Service qui va contenir l'application FRONTEND  
  pokedex-frontend:
    image: nginx:latest
    ports:
      - "808:80"
    volumes : 
      # On monte le dossier FRONTEND dans le dossier racine de Nginx
      - ./app/FRONTEND:/usr/share/nginx/html